services:
  db-golyanytsky:
    image: mysql:8.0
    container_name: db-golyanytsky
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppass123
      MYSQL_ROOT_PASSWORD: root123
    volumes:
      - dbdata:/var/lib/mysql
    # command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network
  wordpress-golyanytsky:
    depends_on:
      - db-golyanytsky
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress-secondname
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: db-golyanytsky:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppass123
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
      - app-network
  webserver-golyanytsky:
    depends_on:
      - wordpress-golyanytsky
    image: nginx:1.15.12-alpine
    container_name: webserver-golyanytsky
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network
volumes:
  wordpress:
    dbdata:
networks:
  app-network:
    driver: bridge
